# Generated by Django 5.0.2 on 2024-02-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default=None, max_length=2083),
            preserve_default=False,
        ),
    ]
