# Generated by Django 5.0.2 on 2024-02-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title']},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title'], name='projects_pr_title_ba614c_idx'),
        ),
    ]
